services:
  - type: web
    name: befit-backend
    runtime: docker
    dockerfilePath: ./fitness-monolith/Dockerfile
    dockerContext: ./fitness-monolith
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DDL_AUTO
        value: update
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false
